### ISSUE TITLE
[FEATURE] Meta data with favicon

### ISSUE THREAD

**Issue by Anmol-Baranwal** [anmode/grabtern-frontend#259]
### Description

A website, especially an open-source one, should have an appropriate favicon and proper meta data for the benefit of crawlers.

I would like to add a favicon based on the official logo of Grabtern.

### Checklist

- [X] I have checked the existing [issues](https://github.com/anmode/grabtern-frontend/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/anmode/grabtern-frontend/blob/develop/CONTRIBUTING.md)
- [X] I would like to be assigned this task.
- [X] I am a GSSoC'23 contributor

**Comment by muskandn** [comment]
I would like to work on this issue under GSSoC'23

**Comment by anmode** [comment]
@Anmol-Baranwal you have assigned a issue.. so assigning this one to @muskandn .

**Comment by Anmol-Baranwal** [comment]
I can work on simultaneous issues, and please dont assign it to anyone else since these are the issues, I would be contributing over upcoming days.

**Comment by anmode** [comment]
As author wants. so assigning this to @Anmol-Baranwal

**Comment by anmode** [comment]
@Anmol-Baranwal ? ARE U UP FOR IT?

**Comment by anmode** [comment]
sure! I was confirming. Thanks
